### ISSUE TITLE
Allow users to select a watershed using the map

### ISSUE THREAD

**Issue by corviday** [pacificclimate/scip-frontend#2]
Travis suggests users might like to select a watershed using the map, instead of a dropdown menu where they have to know the name of their watershed.

I would imagine the Leaflet map toolkit has a way to do that built in, it seems like something a lot of people would want. We'd have a button on the map to trigger watershed selection mode, maybe, then display all the watersheds. After a user picked one, it would go back to displaying only a single watershed outline to help the user understand what data they were viewing now (plus that watershed'd upstream and downstream networks!)

**Comment by rod-glover** [comment]
Sounds like a good idea. If it's helpful, I wrote a JavaScript function that tells you if a given point is inside a polygon. It's presently used to see what stations (locations) are inside a user-provided polygon, but it could easily be used to find what polygon encloses a point clicked by the user. It may be that geoserver or whatever you're using provides this as a backend service, but if you want it in the frontend, it's available.

**Comment by corviday** [comment]
Thanks! I will hit you up when I start on this.

**Comment by corviday** [comment]
Now that we have the postGIS database, and the SCIP backend, an alternate UI seems easier: the user clicks on the map, and the front end queries the backend to get a list of regions that contain that point, and the user selects from amount them somehow, maybe in a popup.

**Comment by rod-glover** [comment]
Yes, you can do it on the backend too. Let me know if you'd like to use the point-in-polygon code for a pure frontend solution. No pressure either way.
