### ISSUE TITLE
Fix selector UI

### ISSUE THREAD

**Issue by corviday** [pacificclimate/scip-frontend#28]
The selectors do not show the already-selected values, so a user won't be able to double-check what they're viewing. Fix this.

**Comment by rod-glover** [comment]
At some point during my [first review](https://github.com/pacificclimate/scip/pull/29), I figured out what the problem was. I should have put the diagnosis here. I'll see if I can dig it up.

**Comment by rod-glover** [comment]
The only evidence I can find is my remark in a previous PR comment that I had a hunch. I am pretty sure it is to do with the distinction between option and value in React Select. That's easy to trip over, and I recall finding the place where you switched from one to the other. We can discuss; I think I can put us onto the right path pretty quickly.

**Comment by corviday** [comment]
I would definitely appreciate that, maybe sometime next week?

**Comment by corviday** [comment]
The issue was: the `value` property of a selector does _not_, as I assumed, want the contents of the `value` attribute of the object emitted by the selector when the user selects an option. It wants the _entire emitted object_.
